### ISSUE TITLE
root access

### ISSUE THREAD

**Issue by nityanantan23** [bryan2894-playgrnd/SimpleWear#1]
im using android 11 and also using magisk with zygisk, while using this application it didn't trigger for root access to use shell commands. went to check the super user list but it wasn't there . how do i solve this

**Comment by thewizrd** [comment]
The Settings helper app (SimpleWear Settings) is the app which uses root
access; the main app doesn't. It should prompt for root access once you
enable the toggle button. If not please check the Superuser tab in Magisk
to check if the app was not accidentally denied root access.

If neither works, please email me a logcat after trying to enable root if
possible.
