### ISSUE TITLE
Already installed but while opening app it shows install in phone

### ISSUE THREAD

**Issue by ultimategyms** [bryan2894-playgrnd/SimpleWear#11]
i have installed the app on both watch(watch 4) and phone (A13) (Also installed Simple Wear settings and granted root permission) and granted all permissions. But when i open the app on watch it shows please install on phone and redirects to app store. Tried reinstalling, restarting both devices but not working. Help Please

**Comment by thewizrd** [comment]
Please check if bluetooth is enabled and connection status is showing connected in the wearable app on your phone
