### ISSUE TITLE
Hotspot toggle not working

### ISSUE THREAD

**Issue by dudebehinddude** [bryan2894-playgrnd/SimpleWear#13]
Issue: toggling hotspot visually turns it off or on on the watch, but it does not change the status of the hotspot on my phone.
✔️ SimplyWear settings is installed and I have gone through ADB to set secure settings

Steps to reproduce:
1. Open SimplyWear on watch or go to the Dashboard tile
2. Enable/disable hotspot
3. The hotspot doesn't actually get turned on or off on my phone

Devices used on:
Motorola One 5g UW
Pixel Watch

**Comment by thewizrd** [comment]
This is working for me on Pixel 5. If this still does not work, please email a copy of logs from phone
