### ISSUE TITLE
Mobile data broken

### ISSUE THREAD

**Issue by MightyM17** [bryan2894-playgrnd/SimpleWear#18]
The app works perfectly on my GW4 and Poco F4, except that I cannot seem to control my mobile data anymore, this could be an android 13 thing.
Here's the logcat from the watch - https://pastebin.com/udGZFhUEn
The toggle just goes back to what it was for the first time, doing it again causes the toggle to change but the changes do not reflect on the mobile

**Comment by thewizrd** [comment]
Unfortunately, looks like you can't toggle mobile data without system permissions. You will need root access or an app like Shizuku to control this.
If your phone is rooted or you are comfortable using Shizuku, please try the latest release.

https://github.com/SimpleAppProjects/SimpleWear/commit/b5c928dc2dbfc49b33710a23959659bc26301074

**Comment by MightyM17** [comment]
> Unfortunately, looks like you can't toggle mobile data without system permissions. You will need root access or an app like Shizuku to control this. If your phone is rooted or you are comfortable using Shizuku, please try the latest release.
> 
> [b5c928d](https://github.com/SimpleAppProjects/SimpleWear/commit/b5c928dc2dbfc49b33710a23959659bc26301074)

Shizuku doesnt detect this app for asking permissions (on 1.13.1 release)

**Comment by thewizrd** [comment]
> > Unfortunately, looks like you can't toggle mobile data without system permissions. You will need root access or an app like Shizuku to control this. If your phone is rooted or you are comfortable using Shizuku, please try the latest release.
> > 
> > [b5c928d](https://github.com/SimpleAppProjects/SimpleWear/commit/b5c928dc2dbfc49b33710a23959659bc26301074)
> 
> Shizuku doesnt detect this app for asking permissions (on 1.13.1 release)

Have you updated or installed the helper app? This latest version has Shizuku integration: https://github.com/SimpleAppProjects/SimpleWear/releases/download/v1.13.1_release/wearsettings-release-1.1.0.apk

**Comment by MightyM17** [comment]
Still broken, will provide the logs later, but the same issue persists, wearsettings 1.1.0, mobile and wear app on 1.13.1

**Comment by MightyM17** [comment]
Nothing in logs, there are no new logs in logcat on button tap weird. But wifi, mobile data both seem to be broken now, I have shizuku up and running on my device
