### ISSUE TITLE
Cannot open media controller by clicking on tile

### ISSUE THREAD

**Issue by perirexcz** [bryan2894-playgrnd/SimpleWear#29]
I am on v1.13.0 and watchUI 5 (galaxy watch 4 classic BT) and since the update to watchUI 5, I am no longer able to open media controller by clicking on the tile. See video.

https://github.com/SimpleAppProjects/SimpleWear/assets/33799459/d5c3da96-7bbf-4d23-a3e9-58fa1f4ca76b

**Comment by perirexcz** [comment]
Additional info: Clicking on "phone control" tile opens the main app without problems.

**Comment by thewizrd** [comment]
Resolved in latest version
