### ISSUE TITLE
Phone lock feature conflicts with Pixel Watch Unlock feature

### ISSUE THREAD

**Issue by Dondrejohnson5** [bryan2894-playgrnd/SimpleWear#41]
Locking the phone with the lock feature from the SimpleWear app disables the Watch Unlock feature from my Pixel Watch 2, as the phone lock feature requires device admin permissions it will disable any other remote means of unlocking the device. Therefore, Watch Unlock cannot unlock the phone when it has previously been "locked by admin." Please change phone lock feature from device admin permissions to accessibility permissions instead, as accessibility allows phone lock to continue functioning as intended, without interfering with Watch Unlock or any other remote unlocking methods.

Watch: Google Pixel Watch 2
Wear OS version: 4
Watch app version: 1.14.0
Phone: Motorola Edge 40 Pro
Phone Android version: 14
Phone app version: 1.13.1

**Comment by thewizrd** [comment]
Hi. That's a good point. I'll look into using an accessibility service instead

**Comment by Dondrejohnson5** [comment]
Thank you. Will this be in beta first? If so, I'll sign up now

**Comment by thewizrd** [comment]
Please check the latest beta. An accessibility service was added as an alternative to the device admin feature.
