### ISSUE TITLE
Opening the SimpleWear app on watch triggers the Google Play page to open on phone, regardless of whether or not the phone app is installed

### ISSUE THREAD

**Issue by Dondrejohnson5** [bryan2894-playgrnd/SimpleWear#44]
The SimpleWear app on the phone is set up with the watch and everything, however in regular use, it gets annoying that every time I open the SimpleWear app on the watch and it reconnects with the phone, it will automatically send the phone to the app's Play Store page, though the app is already installed on the phone and the watch has successfully connected. 
This occurs every time I open/interact with the watch app. The only method of avoiding that bug is using the shortcuts set up on the corresponding tile

Watch: Google Pixel Watch 2
Wear OS version: 4
Watch app version: 1.14.0
Phone: Motorola Edge 40 Pro
Phone Android version: 14
Phone app version: 1.14.0

**Comment by thewizrd** [comment]
Thanks for reporting. This will be resolved in the next update

**Comment by Dondrejohnson5** [comment]
Thank you. Will #41 be as well or is that further down the line?

**Comment by thewizrd** [comment]
> Thank you. Will #41 be as well or is that further down the line?

Yes, i will try to address that as well

**Comment by thewizrd** [comment]
Please check the latest beta. Issue should be resolved
