### ISSUE TITLE
Lacking APKs in releases

### ISSUE THREAD

**Issue by ASGusev** [bryan2894-playgrnd/SimpleWear#46]
For the versions up to 1.13.1 the releases page contains three APKs including the phone and watch apps. For 1.14.0 and 1.15 alpha, however, there is only the settings app

**Comment by ASGusev** [comment]
Play market also shows version 1.13.1

**Comment by thewizrd** [comment]
I've added the apks for v1.14.
v1.15 will be added once its fully released
