### ISSUE TITLE
mobile_data setting broken on multi-sim devices (Android 13, maybe older too)

### ISSUE THREAD

**Issue by Jolanrensen** [bryan2894-playgrnd/SimpleWear#5]
Awesome app! I just discovered it.
However, I did find it cannot control my mobile data connection on my phone. 
The setting, as called in https://github.com/SimpleAppProjects/SimpleWear/blob/master/wearsettings/src/main/java/com/thewizrd/wearsettings/actions/MobileDataAction.kt namely doesn't exist.
My phone is a Pixel 7 Pro and thus allows for multi-sim, meaning that the correct setting for me would be `mobile_data1`.
The simplest solution would be to query which `mobile_data*` keys exist and simply set them all every time. 
A neater solution would be to create a separate setting for each of them, but for me, that wouldn't be necessary.
Finally, we could also have a picker in the settings app on the phone to specify the SIM the watch should control the data setting for.

**Comment by MH-Zarei** [comment]
The same problem with s22ultra and watch5pro

**Comment by Shady-3** [comment]
Same with Note9 SM-N960F/DS with double SIM and Android 10 and GW4. Turning on the data sometimes works and sometimes the data button on the phone gets activated but the data doesn't really connect. On turning it off though it never works, the button gets disactivated on the phone but the data stays on with the 4G in the status bar and when you actually try to browse the internet or anything, you find it's really working although the data button is off on the phone.

**Comment by thewizrd** [comment]
Unfortunately, looks like you can't toggle mobile data without system permissions. You will need root access or an app like Shizuku to control this.
If your phone is rooted or you are comfortable using Shizuku, please try the latest release. It should support multi-sim devices too.

https://github.com/SimpleAppProjects/SimpleWear/commit/b5c928dc2dbfc49b33710a23959659bc26301074
