### ISSUE TITLE
Make the media controller optional

### ISSUE THREAD

**Issue by GrizzlyMove03** [bryan2894-playgrnd/SimpleWear#6]
Hello, ich have the issue, that on my Galaxy Watch (which comes with a already built in media controller), I cant get rid of the media controller, which is detected as an extra app, that I cant uninstall, without removing the whole app. Is there any way to get rid of it, because it really bothers me and the icon is very low quality too. Srry for my bad english
![Screenshot_20221104_001325_sysui](https://user-images.githubusercontent.com/74469659/199853159-8c6735e6-5be9-4173-aa51-9dd4a838019b.png)

**Comment by Antoni-Czaplicki** [comment]
There is an option for this in settings
